package com.strands.agent;

import com.strands.model.Model;
import com.strands.model.ModelConfig;
import com.strands.model.StreamRequest;
import com.strands.tool.AgentTool;
import com.strands.tool.ToolContext;
import com.strands.types.*;
import com.strands.types.streaming.StreamEvent;
import org.junit.jupiter.api.Test;

import java.util.*;

import static org.junit.jupiter.api.Assertions.*;

class AgentBuilderTest {

    @Test
    void testMinimalBuild() {
        Agent agent = Agent.builder()
                .model(new MockModel())
                .build();

        assertNotNull(agent);
        assertNotNull(agent.getAgentId());
        assertNull(agent.getName());
        assertNull(agent.getSystemPrompt());
    }

    @Test
    void testBuildWithAllOptions() {
        Agent agent = Agent.builder()
                .agentId("test-id")
                .name("Test Agent")
                .model(new MockModel())
                .systemPrompt("You are helpful")
                .concurrentInvocationMode(ConcurrentInvocationMode.THROW)
                .build();

        assertEquals("test-id", agent.getAgentId());
        assertEquals("Test Agent", agent.getName());
        assertEquals("You are helpful", agent.getSystemPrompt());
    }

    @Test
    void testBuildWithoutModelThrows() {
        assertThrows(IllegalStateException.class, () ->
                Agent.builder().build());
    }

    @Test
    void testBuildWithTools() {
        AgentTool tool = new AgentTool() {
            @Override
            public String getToolName() {
                return "mytool";
            }

            @Override
            public ToolSpec getToolSpec() {
                return new ToolSpec("mytool", "desc", Map.of("type", "object"));
            }

            @Override
            public ToolResult invoke(ToolUse toolUse, ToolContext context) {
                return ToolResult.success(toolUse.getToolUseId(), "ok");
            }
        };

        Agent agent = Agent.builder()
                .model(new MockModel())
                .tools(tool)
                .build();

        assertTrue(agent.getToolRegistry().contains("mytool"));
    }

    @Test
    void testSetSystemPrompt() {
        Agent agent = Agent.builder()
                .model(new MockModel())
                .systemPrompt("original")
                .build();

        assertEquals("original", agent.getSystemPrompt());
        agent.setSystemPrompt("updated");
        assertEquals("updated", agent.getSystemPrompt());
    }

    @Test
    void testAutoGeneratedAgentId() {
        Agent agent1 = Agent.builder().model(new MockModel()).build();
        Agent agent2 = Agent.builder().model(new MockModel()).build();

        assertNotNull(agent1.getAgentId());
        assertNotNull(agent2.getAgentId());
        assertNotEquals(agent1.getAgentId(), agent2.getAgentId());
    }

    static class MockModel implements Model {
        @Override
        public Iterator<StreamEvent> stream(StreamRequest request) {
            return List.of(
                    StreamEvent.messageStart("assistant"),
                    StreamEvent.contentBlockDelta(0, Map.of("text", "ok")),
                    StreamEvent.messageStop("end_turn"),
                    StreamEvent.metadata(1, 1, 10)
            ).iterator();
        }

        @Override
        public ModelConfig getConfig() {
            return new ModelConfig("mock");
        }

        @Override
        public void updateConfig(Map<String, Object> cfg) {
        }
    }
}
