package examples;

import com.strands.agent.Agent;
import com.strands.agent.AgentResult;
import com.strands.model.bedrock.BedrockModel;
import com.strands.plugin.skills.AgentSkillsPlugin;
import com.strands.plugin.skills.Skill;
import com.strands.plugin.skills.SkillSource;
import com.strands.tool.AgentTool;
import com.strands.tool.Param;
import com.strands.tool.Tool;
import com.strands.tool.mcp.MCPClient;
import com.strands.tool.mcp.StdioMCPTransport;
import software.amazon.awssdk.auth.credentials.ProfileCredentialsProvider;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.bedrockruntime.BedrockRuntimeAsyncClient;

import java.util.ArrayList;
import java.util.List;

/**
 * Example: Combining Skills (progressive disclosure) with MCP tools.
 *
 * This demonstrates the full power of the plugin + tool system:
 *   - Skills provide domain-specific instructions loaded on-demand
 *   - MCP tools provide external capabilities (filesystem, databases, etc.)
 *   - Custom annotated tools provide application-specific logic
 *
 * The agent sees skill descriptions in its system prompt and can activate them
 * when it needs detailed guidance. MCP tools are always available for execution.
 *
 * Usage:
 *   ./gradlew runExample -Pexample=examples.SkillsWithMCPAgent
 */
public class SkillsWithMCPAgent {

    @Tool(name = "get_project_status", description = "Returns the current project status and deadlines")
    public String getProjectStatus() {
        return "Project: Strands Java SDK\n"
                + "Status: In development\n"
                + "Next milestone: v0.2.0 release\n"
                + "Deadline: 2026-06-15\n"
                + "Open tasks: 5 remaining";
    }

    @Tool(name = "format_report", description = "Formats text into a markdown report with headers and sections")
    public String formatReport(
            @Param(value = "title", description = "Report title") String title,
            @Param(value = "content", description = "Raw content to format") String content) {
        return "# " + title + "\n\n"
                + "_Generated: " + java.time.LocalDate.now() + "_\n\n"
                + "## Summary\n\n" + content + "\n\n"
                + "---\n*Report generated by Strands Agent*\n";
    }

    public static void main(String[] args) {
        String profile = System.getenv().getOrDefault("AWS_PROFILE", "default");

        BedrockRuntimeAsyncClient client = BedrockRuntimeAsyncClient.builder()
                .region(Region.US_EAST_1)
                .credentialsProvider(ProfileCredentialsProvider.create(profile))
                .build();

        // --- Skills Setup ---
        // Load skills from the examples/skills directory (code-review, summarization)
        // Plus create an inline skill for report generation
        Skill reportSkill = Skill.builder()
                .name("report-generation")
                .description("Generates formatted project status reports with proper structure")
                .instructions("""
                        When generating a report:
                        1. First call get_project_status to get current data
                        2. Analyze the status information
                        3. Use format_report to create a properly formatted markdown report
                        4. If filesystem tools are available, save the report to a file

                        Report style guidelines:
                        - Lead with the most important finding
                        - Use bullet points for action items
                        - Include dates and deadlines prominently
                        - End with next steps""")
                .allowedTools(List.of("get_project_status", "format_report", "fs_write_file"))
                .build();

        AgentSkillsPlugin skillsPlugin = new AgentSkillsPlugin(
                new SkillSource.Directory(java.nio.file.Path.of("examples/skills")),
                new SkillSource.Direct(reportSkill)
        );

        // --- MCP Setup ---
        // Connect to filesystem MCP server for file operations
        MCPClient mcpClient = new MCPClient(
                new StdioMCPTransport(
                        List.of("npx", "-y", "@modelcontextprotocol/server-filesystem", "/tmp/workspace")
                ),
                30000, null, null, "fs_"
        );

        try {
            mcpClient.start();
            List<AgentTool> mcpTools = mcpClient.loadTools();
            System.out.println("MCP tools loaded: " + mcpTools.size());

            // --- Agent Setup ---
            // Combine: MCP tools + annotated tools + skills plugin (provides skills tool)
            SkillsWithMCPAgent appTools = new SkillsWithMCPAgent();
            List<AgentTool> allTools = new ArrayList<>(mcpTools);

            Agent agent = Agent.builder()
                    .model(new BedrockModel(client, "us.anthropic.claude-sonnet-4-6"))
                    .systemPrompt("You are a project assistant. You have access to:\n"
                            + "- File system tools (fs_*) for reading/writing files\n"
                            + "- Project tools for getting status and formatting reports\n"
                            + "- Skills that provide detailed instructions for complex tasks\n\n"
                            + "When you encounter a task that matches a skill, activate it first to get guidance.")
                    .tools(allTools.toArray(new AgentTool[0]))
                    .toolProviders(appTools)
                    .plugins(skillsPlugin)
                    .build();

            System.out.println("Available skills: " + skillsPlugin.getSkills().keySet());
            System.out.println();

            // --- Example 1: Report generation (will activate the report-generation skill) ---
            System.out.println("=== Task 1: Generate a project report ===");
            AgentResult result1 = agent.invoke(
                    "Generate a project status report and save it to /tmp/workspace/status-report.md");
            System.out.println(result1);
            System.out.println("\nActivated skills: " + skillsPlugin.getActivatedSkills());
            System.out.println();

            // --- Example 2: Summarization (will activate the summarization skill) ---
            System.out.println("=== Task 2: Summarize a document ===");
            AgentResult result2 = agent.invoke(
                    "Read the file /tmp/workspace/status-report.md and provide a 2-sentence summary of it.");
            System.out.println(result2);
            System.out.println("\nActivated skills: " + skillsPlugin.getActivatedSkills());

        } finally {
            mcpClient.close();
        }
    }
}
